version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl-app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "run_pipeline.py"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: etl_db

volumes:
  postgres_data: